Repository apache/knox, pull requests merged in 2021-07, with the labels that each got.

#461 KNOX-2624 - Introducing Knox Token Management UI
  gateway-applications/pom.xml
  gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/JWTMessages.java
  gateway-provider-security-jwt/src/main/java/org/apache/knox/gateway/provider/federation/jwt/filter/AbstractJWTFilter.java
  gateway-provider-security-jwt/src/test/java/org/apache/knox/gateway/provider/federation/TokenIDAsHTTPBasicCredsFederationFilterTest.java
  gateway-release/home/conf/gateway-site.xml
  gateway-release/home/conf/topologies/homepage.xml
  gateway-release/pom.xml
  gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/DefaultTokenStateService.java
  gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/JDBCTokenStateService.java
  gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateDatabase.java
  gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/TokenStateServiceMessages.java
  gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
  gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
  gateway-spi/pom.xml
  gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/KnoxToken.java
  gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenMetadata.java
  gateway-spi/src/main/java/org/apache/knox/gateway/services/security/token/TokenStateService.java
  knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.html
  knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.ts
  knox-token-management-ui/.gitignore
  knox-token-management-ui/angular-cli.json
  knox-token-management-ui/npm
  knox-token-management-ui/package-lock.json
  knox-token-management-ui/package.json
  knox-token-management-ui/pom.xml
  knox-token-management-ui/proxy.conf.json
  knox-token-management-ui/src/main/resources/token-management/service.xml
  knox-token-management-ui/token-management/app/app.module.ts
  knox-token-management-ui/token-management/app/knox.token.ts
  knox-token-management-ui/token-management/app/metadata.ts
  knox-token-management-ui/token-management/app/token.management.component.html
  knox-token-management-ui/token-management/app/token.management.component.ts
  knox-token-management-ui/token-management/app/token.management.service.ts
  knox-token-management-ui/token-management/assets/knox-logo-transparent.gif
  knox-token-management-ui/token-management/assets/sticky-footer.css
  knox-token-management-ui/token-management/environments/environment.prod.ts
  knox-token-management-ui/token-management/environments/environment.ts
  knox-token-management-ui/token-management/favicon.ico
  knox-token-management-ui/token-management/index.html
  knox-token-management-ui/token-management/main.ts
  knox-token-management-ui/token-management/polyfills.ts
  knox-token-management-ui/token-management/styles.css
  knox-token-management-ui/token-management/tsconfig.json
  knox-token-management-ui/tslint.json
  pom.xml
Labels: knoxtoken

#462 KNOX-2628 - Metadata and issue time aliases are removed too during token revocation
  gateway-server/src/main/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateService.java
  gateway-server/src/test/java/org/apache/knox/gateway/services/token/impl/AliasBasedTokenStateServiceTest.java
Labels: knoxtoken

#463 KNOX-2627 - Limiting the number of managed tokens per user
  gateway-server/src/main/java/org/apache/knox/gateway/config/impl/GatewayConfigImpl.java
  gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
  gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceMessages.java
  gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
  gateway-spi/src/main/java/org/apache/knox/gateway/config/GatewayConfig.java
  gateway-test-release-utils/src/main/java/org/apache/knox/gateway/GatewayTestConfig.java
  gateway-util-common/src/main/java/org/apache/knox/gateway/util/JsonUtils.java
Labels: knoxtoken

#465 KNOX-2629 - Fix new shellcheck errors
  .travis.yml
  gateway-release-common/home/bin/knox-functions.sh
  gateway-release-common/pom.xml
  gateway-release/home/bin/gateway.sh
  gateway-release/pom.xml
  gateway-shell-release/pom.xml
  pom.xml
Labels: Build

#468 KNOX-2633 - Handling supplied client data with multiple '=' signs when generating a token
  gateway-release/home/conf/topologies/homepage.xml
  gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
  gateway-service-knoxtoken/src/test/java/org/apache/knox/gateway/service/knoxtoken/TokenServiceResourceTest.java
Labels: knoxtoken

#464 KNOX-2626. Support MySQL in JDBCTokenStateService
  gateway-server/pom.xml
  gateway-server/src/main/java/org/apache/knox/gateway/util/JDBCUtils.java
  gateway-server/src/test/java/org/apache/knox/gateway/util/JDBCUtilsTest.java
  pom.xml
Labels: knoxtoken

#467 KNOX-2632 - Properly copying generated content on tokengen UI
  gateway-applications/src/main/resources/applications/tokengen/app/index.html
  gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
Labels: knoxtoken

#466 KNOX-2630. BadUrlTest and BadBackendTest are flaky (amagyar)
  gateway-server/src/test/java/org/apache/knox/gateway/websockets/BadBackendTest.java
  gateway-server/src/test/java/org/apache/knox/gateway/websockets/BadUrlTest.java
Labels: Build, Testing

#470 KNOX-2635 - GatewayAppFuncTest is flaky
  gateway-test/src/test/java/org/apache/knox/gateway/GatewayAppFuncTest.java
Labels: Testing

#471 KNOX-2637 - Added a new Knox CLI command to generate JWK secrets
  gateway-server/src/main/java/org/apache/knox/gateway/util/KnoxCLI.java
  gateway-server/src/test/java/org/apache/knox/gateway/util/KnoxCLITest.java
Labels: KnoxCLI
