Repository apache/knox, pull requests merged in 2022-11, with the labels that each got.

#656 KNOX-2811 - Change token generation application from js to angular
  gateway-applications/pom.xml
  gateway-applications/src/main/resources/applications/tokengen/app/index.html
  gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
  gateway-applications/src/main/resources/applications/tokengen/app/libs/bower/jquery/js/jquery-3.5.1.min.js
  gateway-release/home/conf/topologies/homepage.xml
  gateway-release/pom.xml
  knox-homepage-ui/home/app/generalProxyInformation/general.proxy.information.component.ts
  knox-token-generation-ui/.gitignore
  knox-token-generation-ui/angular-cli.json
  knox-token-generation-ui/npm
  knox-token-generation-ui/package-lock.json
  knox-token-generation-ui/package.json
  knox-token-generation-ui/pom.xml
  knox-token-generation-ui/proxy.conf.json
  knox-token-generation-ui/src/main/resources/token-gen/service.xml
  knox-token-generation-ui/token-generation/app/app.module.ts
  knox-token-generation-ui/token-generation/app/token-generation.component.html
  knox-token-generation-ui/token-generation/app/token-generation.component.ts
  knox-token-generation-ui/token-generation/app/token-generation.models.ts
  knox-token-generation-ui/token-generation/app/token-generation.service.ts
  knox-token-generation-ui/token-generation/assets/fonts/fontawesome/FontAwesome.otf
  knox-token-generation-ui/token-generation/assets/fonts/fontawesome/fontawesome-webfont.eot
  knox-token-generation-ui/token-generation/assets/fonts/fontawesome/fontawesome-webfont.svg
  knox-token-generation-ui/token-generation/assets/fonts/fontawesome/fontawesome-webfont.ttf
  knox-token-generation-ui/token-generation/assets/fonts/fontawesome/fontawesome-webfont.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-300.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-300i.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-400.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-400i.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-600.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-600i.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-700.woff
  knox-token-generation-ui/token-generation/assets/fonts/fontopensans/open-sans-700i.woff
  knox-token-generation-ui/token-generation/assets/images/avatar.png
  knox-token-generation-ui/token-generation/assets/images/blank.gif
  knox-token-generation-ui/token-generation/assets/images/favicon.ico
  knox-token-generation-ui/token-generation/assets/images/knox-logo-white-bg.gif
  knox-token-generation-ui/token-generation/assets/images/knox-logo.gif
  knox-token-generation-ui/token-generation/assets/images/loading.gif
  knox-token-generation-ui/token-generation/assets/knox-logo-transparent.gif
  knox-token-generation-ui/token-generation/assets/sticky-footer.css
  knox-token-generation-ui/token-generation/assets/styles/app-font.css
  knox-token-generation-ui/token-generation/assets/styles/bootstrap.min.css
  knox-token-generation-ui/token-generation/assets/styles/knox.css
  knox-token-generation-ui/token-generation/environments/environment.prod.ts
  knox-token-generation-ui/token-generation/environments/environment.ts
  knox-token-generation-ui/token-generation/favicon.ico
  knox-token-generation-ui/token-generation/index.html
  knox-token-generation-ui/token-generation/main.ts
  knox-token-generation-ui/token-generation/polyfills.ts
  knox-token-generation-ui/token-generation/styles.css
  knox-token-generation-ui/token-generation/tsconfig.json
  knox-token-generation-ui/tslint.json
  knox-token-management-ui/token-management/app/token.management.component.ts
  pom.xml
Labels: knoxtoken

#668 KNOX-2832 - Move DoSFilter into WebAppSec
  gateway-provider-jersey/src/main/java/org/apache/knox/gateway/jersey/JerseyServiceDeploymentContributorBase.java
  gateway-provider-security-dos/pom.xml
  gateway-provider-security-dos/src/main/java/org/apache/knox/gateway/deploy/impl/DosFilterDeploymentContributor.java
  gateway-provider-security-dos/src/main/resources/META-INF/services/org.apache.knox.gateway.deploy.ProviderDeploymentContributor
  gateway-provider-security-webappsec/pom.xml
  gateway-provider-security-webappsec/src/main/java/org/apache/knox/gateway/webappsec/deploy/WebAppSecContributor.java
  gateway-provider-security-webappsec/src/test/java/org/apache/knox/gateway/webappsec/deploy/WebAppSecContributorTest.java
  gateway-release/pom.xml
  gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ApplicationDeploymentContributor.java
  gateway-server/src/main/java/org/apache/knox/gateway/deploy/impl/ServiceDefinitionDeploymentContributor.java
  gateway-spi/src/main/java/org/apache/knox/gateway/deploy/ServiceDeploymentContributorBase.java
  pom.xml
Labels: webappsec

#675 KNOX-2830 - Disabled Travis CI integration
  .travis.yml.disabled
Labels: Build, TravisCI

#684 KNOX-2846 - Disabling org.apache.knox.gateway.websockets.GatewayWebsocketHandlerTest.testValidWebShellRequest()
  gateway-server/src/test/java/org/apache/knox/gateway/websockets/GatewayWebsocketHandlerTest.java
Labels: Build
